#!/bin/bash

# Script pour appliquer la migration sub_polygon à search_listings
# Usage: ./scripts/apply-sub-polygon-migration.sh

echo "📋 Application de la migration sub_polygon pour search_listings..."
echo ""
echo "Option 1: Via le Dashboard Supabase (RECOMMANDÉ - Le plus simple)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Allez sur votre dashboard Supabase: https://supabase.com/dashboard"
echo "2. Sélectionnez votre projet"
echo "3. Cliquez sur 'SQL Editor' dans le menu de gauche"
echo "4. Cliquez sur 'New query'"
echo "5. Copiez-collez le contenu du fichier:"
echo "   supabase/migrations/20240101000012_add_sub_polygon_to_search.sql"
echo "6. Cliquez sur 'Run' ou appuyez sur Cmd+Enter"
echo ""
echo "Option 2: Installer Supabase CLI (pour automatiser)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Sur macOS (via Homebrew):"
echo "  brew install supabase/tap/supabase"
echo ""
echo "Puis connectez-vous:"
echo "  supabase login"
echo ""
echo "Et appliquez la migration:"
echo "  supabase db push"
echo ""
echo "Option 3: Via psql (si vous avez la connection string)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Obtenez la connection string depuis:"
echo "  Dashboard > Settings > Database > Connection string"
echo ""
echo "Puis exécutez:"
echo "  psql 'VOTRE_CONNECTION_STRING' -f supabase/migrations/20240101000012_add_sub_polygon_to_search.sql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANT: Cette migration modifie la fonction search_listings"
echo "   pour inclure sub_polygon et sub_polygon_color dans les résultats."
echo ""
echo "Le fichier de migration se trouve ici:"
echo "  $(pwd)/supabase/migrations/20240101000012_add_sub_polygon_to_search.sql"
echo ""
