#!/bin/bash

# Script pour appliquer le correctif de la fonction search_listings
# Usage: ./scripts/apply-fix-search-listings.sh

echo "🔧 Application du correctif pour search_listings (résout l'ambiguïté)..."
echo ""
echo "Option 1: Via le Dashboard Supabase (RECOMMANDÉ - Le plus simple)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Allez sur votre dashboard Supabase: https://supabase.com/dashboard"
echo "2. Sélectionnez votre projet"
echo "3. Cliquez sur 'SQL Editor' dans le menu de gauche"
echo "4. Cliquez sur 'New query'"
echo "5. Copiez-collez le contenu du fichier:"
echo "   supabase/migrations/20240101000013_fix_search_listings_ambiguity.sql"
echo "6. Cliquez sur 'Run' ou appuyez sur Cmd+Enter"
echo ""
echo "⚠️  IMPORTANT: Cette migration supprime toutes les anciennes versions"
echo "   de search_listings et crée une seule version complète."
echo ""
echo "Option 2: Installer Supabase CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Sur macOS (via Homebrew):"
echo "  brew install supabase/tap/supabase"
echo ""
echo "Puis connectez-vous et appliquez la migration:"
echo "  supabase login"
echo "  supabase db push"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Le fichier de migration se trouve ici:"
echo "  $(pwd)/supabase/migrations/20240101000013_fix_search_listings_ambiguity.sql"
echo ""
